from __future__ import annotations

from pathlib import Path

from .constants import BLOB_EXTENSIONS, BLOB_FOLDERS, PARTITION_DIRS
from .utils import iter_files, relative_posix, unique_sorted, write_text


class BlobGenerator:
    """Create proprietary-files style blob lists from firmware dumps."""

    def __init__(self, root: Path | str):
        self.root = Path(root).expanduser().resolve()

    def collect(self) -> list[str]:
        blobs: list[str] = []
        for path in iter_files(self.root):
            rel = relative_posix(path, self.root)
            rel_lower = f"/{rel.lower()}"
            partition = rel.split("/", 1)[0]
            if partition not in PARTITION_DIRS:
                continue
            if self._is_blob(rel_lower, path):
                blobs.append(rel)
        return unique_sorted(blobs)

    def write(self, output: Path | str) -> list[str]:
        blobs = self.collect()
        content = render_proprietary_files(blobs)
        write_text(Path(output), content)
        return blobs

    @staticmethod
    def _is_blob(rel_lower: str, path: Path) -> bool:
        if path.suffix.lower() in BLOB_EXTENSIONS:
            return True
        return any(folder in rel_lower for folder in BLOB_FOLDERS)


def render_proprietary_files(blobs: list[str]) -> str:
    header = [
        "# Proprietary files generated by DroidFoundry",
        "# Review this list before using it in a production device tree.",
        "# Keep only blobs required for your device and ROM target.",
        "",
    ]
    if not blobs:
        return "\n".join(header + ["# No candidate blobs were found.", ""])

    lines = header
    current_section = ""
    for blob in blobs:
        section = blob.split("/", 2)[:2]
        section_name = "/".join(section) if len(section) >= 2 else blob.split("/", 1)[0]
        if section_name != current_section:
            if current_section:
                lines.append("")
            lines.append(f"# {section_name}")
            current_section = section_name
        lines.append(blob)
    lines.append("")
    return "\n".join(lines)
