from __future__ import annotations

from pathlib import Path

from .scanner import FirmwareScanner
from .utils import normalize_name, write_text, safe_read_text


def build_boardconfig_hints(dump: Path | str, brand: str | None = None, device: str | None = None) -> str:
    scan = FirmwareScanner(dump).scan()
    meta = scan.metadata
    vendor = normalize_name(brand or meta.brand or meta.manufacturer)
    codename = normalize_name(device or meta.device)
    platform = meta.platform if meta.platform != "unknown" else "review_platform"
    uses_dynamic = "super.img" in {p.name.lower() for p in scan.images} or "system_ext" in scan.partitions
    image_names = {p.name.lower() for p in scan.images}
    fstab_text = "\n".join(safe_read_text(p, limit=500_000).lower() for p in scan.fstab_files)
    has_ab = any(name.endswith(("_a.img", "_b.img")) for name in image_names) or "slotselect" in fstab_text or "ab_ota" in fstab_text
    has_vendor_boot = "vendor_boot.img" in image_names
    first_api = meta.first_api_level if meta.first_api_level != "unknown" else "review_first_api_level"

    lines = [
        "# BoardConfig hints generated by DroidFoundry",
        "# These values are hints from firmware metadata. Review every line before using.",
        "",
        f"BOARD_VENDOR := {vendor}",
        f"TARGET_BOOTLOADER_BOARD_NAME := {codename}",
        f"TARGET_OTA_ASSERT_DEVICE := {codename}",
        f"TARGET_BOARD_PLATFORM := {platform}  # review this value",
        "TARGET_ARCH := arm64  # review this value",
        "TARGET_ARCH_VARIANT := armv8-a  # review this value",
        "TARGET_CPU_ABI := arm64-v8a  # review this value",
        "TARGET_CPU_ABI2 :=  # review this value",
        "TARGET_CPU_VARIANT := generic  # review this value",
        "",
        "# Partitions",
        "TARGET_COPY_OUT_VENDOR := vendor",
    ]
    if "product" in scan.partitions:
        lines.append("TARGET_COPY_OUT_PRODUCT := product")
    if "system_ext" in scan.partitions:
        lines.append("TARGET_COPY_OUT_SYSTEM_EXT := system_ext")
    if "odm" in scan.partitions:
        lines.append("TARGET_COPY_OUT_ODM := odm")
    if uses_dynamic:
        lines.extend(
            [
                "BOARD_USES_DYNAMIC_PARTITIONS := true  # review partition groups",
                "BOARD_SUPER_PARTITION_SIZE := 0  # fill from stock partition table",
                "BOARD_SUPER_PARTITION_GROUPS := main  # review group name",
                "BOARD_MAIN_SIZE := 0  # fill from stock partition table",
                "BOARD_MAIN_PARTITION_LIST := system vendor product system_ext odm  # review list",
            ]
        )
    if has_ab:
        lines.extend(
            [
                "AB_OTA_UPDATER := true  # detected A/B hints, review before using",
                "AB_OTA_PARTITIONS += boot vendor_boot dtbo vbmeta system vendor product system_ext",
            ]
        )
    if has_vendor_boot:
        lines.append("BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true  # review ramdisk layout")

    lines.extend(
        [
            "",
            "# VNDK / API",
            "BOARD_VNDK_VERSION := current",
            f"PRODUCT_SHIPPING_API_LEVEL := {first_api}  # review this value",
            "",
            "# Hardware hints",
            "BOARD_USES_QCOM_HARDWARE := true  # remove if not Qualcomm",
            "TARGET_USES_64_BIT_BINDER := true  # review this value",
            "",
        ]
    )
    return "\n".join(lines)


def write_boardconfig_hints(dump: Path | str, output: Path | str, brand: str | None = None, device: str | None = None) -> str:
    content = build_boardconfig_hints(dump, brand=brand, device=device)
    write_text(Path(output), content)
    return content
