from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from .blobs import BlobGenerator
from .utils import write_text

CATEGORY_PATTERNS: "OrderedDict[str, tuple[str, ...]]" = OrderedDict(
    [
        ("Camera", ("camera", "camx", "chi", "imx", "ov", "s5k", "eeprom")),
        ("Audio", ("audio", "audioserver", "sound", "mixer", "acdb", "alsa", "tinyalsa", "agm", "pal")),
        ("Display", ("display", "drm", "gralloc", "composer", "hwcomposer", "qdcm", "mapper", "memtrack")),
        ("Graphics", ("egl", "gles", "vulkan", "gpu", "adreno", "kgsl", "libgsl", "libllvm")),
        ("Bluetooth", ("bluetooth", "bt_", "bt-", "btconfig", "btfm", "libbt", "bta")),
        ("Wi-Fi", ("wifi", "wlan", "wcn", "cnss", "qca", "iwlwifi", "hostapd", "wpa_supplicant")),
        ("Radio", ("radio", "rild", "ril", "qcril", "modem", "ims", "qmi", "qti", "telephony", "mbn")),
        ("GPS", ("gps", "gnss", "izat", "loc_api", "location")),
        ("Sensors", ("sensor", "sensors", "sns", "akm", "bmi", "bosch", "lsm", "imu")),
        ("Fingerprint", ("fingerprint", "fp", "goodix", "fpc", "egistec", "udfps", "biometrics")),
        ("NFC", ("nfc", "pn5", "nq", "ese", "secure_element")),
        ("Power", ("power", "battery", "charger", "health", "thermal-engine", "perf", "powerhint")),
        ("Thermal", ("thermal", "therm", "temp")),
        ("Media", ("media", "codec", "omx", "c2", "mm-video", "stagefright", "extractor")),
        ("DRM", ("widevine", "drm", "clearkey", "oemcrypto", "keymaster", "gatekeeper")),
        ("VINTF and Permissions", ("vintf", "manifest.xml", "compatibility_matrix", "permissions", "sysconfig")),
        ("Init and Fstab", ("init", "fstab", ".rc")),
        ("Firmware", ("firmware", ".mbn", ".elf", ".fw", ".b00", ".b01", ".b02", ".b03")),
        ("Apps and Framework", ("/app/", "/priv-app/", "/framework/", ".apk", ".jar", ".apex")),
        ("Input and Keylayout", ("/usr/keylayout", "/usr/keychars", ".kl", ".kcm", ".idc")),
    ]
)

FALLBACK_CATEGORY = "Other Proprietary Files"


def classify_blob(path: str) -> str:
    """Return a maintainer-friendly category for one proprietary file path."""
    normalized = f"/{path.lower()}"
    for category, patterns in CATEGORY_PATTERNS.items():
        if any(pattern in normalized for pattern in patterns):
            return category
    if normalized.endswith(".so") or "/lib/" in normalized or "/lib64/" in normalized:
        return "Native Libraries"
    if normalized.endswith(".xml"):
        return "XML Configuration"
    if normalized.endswith((".conf", ".cfg", ".json", ".ini")):
        return "Configuration"
    return FALLBACK_CATEGORY


def classify_blobs(blobs: list[str]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = OrderedDict()
    for blob in sorted(set(blobs)):
        grouped.setdefault(classify_blob(blob), []).append(blob)
    return grouped


def render_grouped_proprietary_files(blobs: list[str]) -> str:
    grouped = classify_blobs(blobs)
    lines = [
        "# Proprietary files generated by DroidFoundry",
        "# Grouped by likely hardware area. Review before using in a production device tree.",
        "# Remove entries that are not required by your ROM/device target.",
        "",
    ]
    if not grouped:
        lines.extend(["# No candidate proprietary files were found.", ""])
        return "\n".join(lines)

    for category, paths in grouped.items():
        lines.append(f"# {category}")
        lines.extend(paths)
        lines.append("")
    return "\n".join(lines)


def write_grouped_blobs(dump: Path | str, output: Path | str) -> dict[str, list[str]]:
    blobs = BlobGenerator(dump).collect()
    grouped = classify_blobs(blobs)
    write_text(Path(output), render_grouped_proprietary_files(blobs))
    return grouped
