from __future__ import annotations

from pathlib import Path

from .hardware import build_hardware_map
from .properties_intel import property_summary
from .recommendations import recommended_next_steps
from .scanner import FirmwareScanner
from .scoring import compute_readiness_score
from .utils import normalize_name, write_json, write_text


def export_rom_harbor(dump: Path | str, output: Path | str) -> list[Path]:
    out = Path(output).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    scan = FirmwareScanner(dump).scan()
    meta = scan.metadata
    hardware = build_hardware_map(dump)
    score = compute_readiness_score(dump)
    device = normalize_name(meta.device)
    brand = normalize_name(meta.brand)

    device_json = {
        "codename": device,
        "brand": brand,
        "name": meta.model if meta.model != "unknown" else device,
        "maintainer": "Manish Kishore",
        "androidVersion": meta.android_version,
        "securityPatch": meta.security_patch,
        "buildFingerprint": meta.fingerprint,
        "platform": meta.platform,
        "bringupScore": score.percentage,
        "hardware": [entry.to_dict() for entry in hardware],
    }
    notes = [
        f"# ROM Harbor Notes for {meta.model if meta.model != 'unknown' else device}",
        "",
        f"- Device: `{device}`",
        f"- Brand: `{brand}`",
        f"- Android: `{meta.android_version}`",
        f"- Security patch: `{meta.security_patch}`",
        f"- Bring-up readiness: `{score.total}/{score.maximum}`",
        "",
        "## Recommended next steps",
        "",
    ]
    notes.extend(f"- {step}" for step in recommended_next_steps(dump))
    files = [
        out / "rom-harbor-device.json",
        out / "rom-harbor-hardware-map.json",
        out / "rom-harbor-release-notes.md",
    ]
    write_json(files[0], device_json)
    write_json(files[1], [entry.to_dict() for entry in hardware])
    write_text(files[2], "\n".join(notes) + "\n")
    return files


def export_android_es(dump: Path | str, output: Path | str, rom: str = "lineage") -> list[Path]:
    out = Path(output).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    scan = FirmwareScanner(dump).scan()
    meta = scan.metadata
    props = property_summary(dump)
    device = normalize_name(meta.device)
    brand = normalize_name(meta.brand)
    lunch = f"{normalize_name(rom)}_{device}-userdebug"
    profile = f'''# Android ES profile generated by DroidFoundry
DEVICE="{device}"
BRAND="{brand}"
MODEL="{meta.model}"
ANDROID_VERSION="{meta.android_version}"
SECURITY_PATCH="{meta.security_patch}"
PLATFORM="{meta.platform}"
LUNCH="{lunch}"
DEVICE_PATH="device/{brand}/{device}"
VENDOR_PATH="vendor/{brand}/{device}"
KERNEL_PATH="kernel/{brand}/{device}"
'''
    report = [
        f"# Android ES Report for {device}",
        "",
        f"- Device: `{device}`",
        f"- Brand: `{brand}`",
        f"- Model: `{meta.model}`",
        f"- Android: `{meta.android_version}`",
        f"- Security patch: `{meta.security_patch}`",
        f"- Platform: `{meta.platform}`",
        f"- Shipping API: `{props.get('Shipping API level', 'unknown')}`",
        "",
        "Use the profile file as a starting point for Android ES device configuration.",
        "",
    ]
    files = [out / "android-es-profile.conf", out / "android-es-report.md"]
    write_text(files[0], profile)
    write_text(files[1], "\n".join(report))
    return files
